### ISSUE TITLE
Checkbox switch slides to wrong side

### ISSUE THREAD

**Issue by MLDMoritz** [MahdiMajidzadeh/bootstrap-v4-rtl#60]
![image](https://user-images.githubusercontent.com/46711821/76688350-36ab1f80-662c-11ea-87a0-06d14485c14b.png)

![image](https://user-images.githubusercontent.com/46711821/76688347-301ca800-662c-11ea-9bc9-c2a6e16a1464.png)

**Comment by MLDMoritz** [comment]
I "solved"? with:

```scss
.rtl {
    .custom-control-input:checked ~ .custom-control-label {
      &::after {
        transform: translateX(-($b-custom-switch-width-lg - $b-custom-control-indicator-size-lg))!important;
      }
    }
}
```
